name: Lint and test the files to ensure code quality
on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Run linter, formatter, test, and coverage
        run: npm run lint && npm run format && npm run test:ci && npm run test:cov
